#+title: liskk.el
#+author: Naoya Yamashita

[[https://github.com/conao3/liskk.el][https://raw.githubusercontent.com/conao3/files/master/blob/headers/png/liskk.el.png]]

[[https://github.com/conao3/liskk.el/blob/master/LICENSE][https://img.shields.io/github/license/conao3/liskk.el.svg?style=flat-square]]
[[https://github.com/conao3/liskk.el/releases][https://img.shields.io/github/tag/conao3/liskk.el.svg?style=flat-square]]
[[https://github.com/conao3/liskk.el/actions][https://github.com/conao3/liskk.el/workflows/Main%20workflow/badge.svg]]

A lightweight Japanese input method for Emacs, inspired by [[https://github.com/skk-dev/ddskk][DDSKK]].

* Overview

=liskk= provides Simple Kana to Kanji conversion (SKK) functionality for Emacs. The name comes from "risk" -- this project is experimental but offers a fresh take on Japanese input in Emacs.

** Features

- Roman-to-kana conversion with customizable rules
- Support for hiragana, katakana, and half-width katakana
- Compatible with standard SKK dictionary files
- Automatic dictionary download from the =liskk-dict.el= repository
- Lightweight alternative to DDSKK

** Requirements

- Emacs 25.1 or later
- [[https://github.com/emacsorphanage/ov][ov.el]] (overlay library)

* Installation

=liskk.el= is not yet available on MELPA. You can install it manually or using a package manager.

** Using leaf.el with el-get

#+begin_src emacs-lisp
(leaf liskk
  :el-get conao3/liskk.el)
#+end_src

** Manual Installation

Clone the repository and add it to your =load-path=:

#+begin_src emacs-lisp
(add-to-list 'load-path (locate-user-emacs-file "site-lisp/liskk.el"))
(require 'liskk)
#+end_src

* Usage

Enable =liskk-mode= in any buffer to start using Japanese input:

#+begin_src emacs-lisp
M-x liskk-mode
#+end_src

The mode indicator shows the current input state:
- =[かな]= -- Hiragana mode
- =[カナ]= -- Katakana mode
- =[半カナ]= -- Half-width katakana mode

* Configuration

** Custom Conversion Rules

You can extend the default roman-to-kana rules:

#+begin_src emacs-lisp
(setq liskk-rule-roman-kana-alist
  '(("hh" "h" ("ッ" . "っ"))
    ("@" nil "＠")))
#+end_src

After modifying rules, restart liskk with =M-x liskk-restart=.

** Dictionary Settings

Configure dictionary paths to customize your setup:

#+begin_src emacs-lisp
;; Personal dictionary (saved automatically)
(setq liskk-personal-dict-path
  (locate-user-emacs-file "liskk/personal.L"))

;; Shared dictionaries (searched after personal dictionary)
(setq liskk-shared-dict-path-list
  (list (locate-user-emacs-file "liskk/SKK-JISYO.L")))
#+end_src

* Contributing

Contributions are welcome. Feel free to open issues or submit pull requests on [[https://github.com/conao3/liskk.el][GitHub]].

* License

#+begin_example
Affero General Public License Version 3 (AGPLv3)
Copyright (c) Naoya Yamashita - https://conao3.com
https://github.com/conao3/liskk.el/blob/master/LICENSE
#+end_example

* Author

Naoya Yamashita ([[https://github.com/conao3][conao3]])
